// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXhUWfAKKZkMCX5_t3ypasL7nuH2s7SLE',
    appId: '1:951283294389:web:b2a7e301e47e230fe5defc',
    messagingSenderId: '951283294389',
    projectId: 'pushnotifications-7063f',
    authDomain: 'pushnotifications-7063f.firebaseapp.com',
    storageBucket: 'pushnotifications-7063f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Z3azJrgY7ltFFZjCFubiwfqDQ3AJ5pE',
    appId: '1:951283294389:android:922f7d84fdfdbd67e5defc',
    messagingSenderId: '951283294389',
    projectId: 'pushnotifications-7063f',
    storageBucket: 'pushnotifications-7063f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVp4gU9AHdJPag3ULKq-hz_nhVjLmCAA',
    appId: '1:951283294389:ios:e7e651612c9c2113e5defc',
    messagingSenderId: '951283294389',
    projectId: 'pushnotifications-7063f',
    storageBucket: 'pushnotifications-7063f.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtVp4gU9AHdJPag3ULKq-hz_nhVjLmCAA',
    appId: '1:951283294389:ios:e7e651612c9c2113e5defc',
    messagingSenderId: '951283294389',
    projectId: 'pushnotifications-7063f',
    storageBucket: 'pushnotifications-7063f.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXhUWfAKKZkMCX5_t3ypasL7nuH2s7SLE',
    appId: '1:951283294389:web:8d50ec900f47bcede5defc',
    messagingSenderId: '951283294389',
    projectId: 'pushnotifications-7063f',
    authDomain: 'pushnotifications-7063f.firebaseapp.com',
    storageBucket: 'pushnotifications-7063f.firebasestorage.app',
  );
}
